version: '3.1'

services:

  rabbitmq:
    image: rabbitmq:3-management
    domainname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  microservice-a-java-instance-1:
    image: microservice-a-example.jar
    restart: always
    build: ./
    ports:
        - 2220:2222
    depends_on:
      - rabbitmq

  microservice-a-java-instance-2:
    image: microservice-a-example.jar
    restart: always
    build: ./
    ports:
      - 2221:2222
    depends_on:
      - rabbitmq

  microservice-a-java-instance-3:
    image: microservice-a-example.jar
    restart: always
    build: ./
    ports:
      - 2222:2222
    depends_on:
      - rabbitmq

  microservice-b-python:
    build: ./consumer_1
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - rabbitmq

  microservice-c-js:
    build: ./consumer_2
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - rabbitmq

  load-balancer:
    build:
      context: ./nginx_configuration
    ports:
      - 9090:9090
    depends_on:
      - microservice-a-java-instance-1
      - microservice-a-java-instance-2
      - microservice-a-java-instance-3
