version: '3.1'

services:

#  microserviceDb:
#    image: postgres:12-alpine
#    restart: always
#    environment:
#      POSTGRES_PASSWORD: p0stgres
#      POSTGRES_USER: postgres
#      POSTGRES_DB: microserviceUser
#    ports:
#      - 5432:5432

#  pgMyAdmin:
#    image: dpage/pgadmin4
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: user@domain.com
#      PGADMIN_DEFAULT_PASSWORD: SuperSecret
#    ports:
#      - 80:80

  rabbitmq:
    image: rabbitmq:3-management
    domainname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  microservice-a-java:
    image: microservice-a-example.jar
    restart: always
    build: ./
    ports:
        - 2222:2222
    depends_on:
#      - microserviceDb
      - rabbitmq

  microservice-b-python:
    build: ./consumer_1
    restart: always
    ports:
      - 5000:5000
    depends_on:
#      - microserviceDb
      - rabbitmq

  microservice-c-js:
    build: ./consumer_2
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - rabbitmq
#      - microserviceDb

